### ISSUE TITLE
Investigate adding usage stats for API

### ISSUE THREAD

**Issue by decentral1se** [giving-a-fuck-about-climate-change/carbondoomsday#100]
Coming from https://github.com/giving-a-fuck-about-climate-change/carbon-inferno/issues/124#issuecomment-355658160.

I won't use Google analytics. I'm interested to see how this can be done fairly.

**Comment by eigenhombre** [comment]
I understand you're moving to Digital Ocean, which does have usage graphs.  Or are you looking for something public-facing?

**Comment by lwm** [comment]
That's a good point, DO does have basic usage graphs.

I just saw https://matomo.org/features/ and was like, woah, what a feature set, I want that.

Probably quite easy to setup (another container somewhere on the toaster).
