### ISSUE TITLE
Start packaging scraped data using known data format

### ISSUE THREAD

**Issue by decentral1se** [giving-a-fuck-about-climate-change/carbondoomsday#105]
I don't really have much knowledge here but I think we should be providing the data that we scrape in other formats beside the web API access (which is suited to web developers). Other people (including the open climate data people) are more focused on different formats. We should do that also. Some contenders:

  * https://datahub.io/ (for example, https://datahub.io/core/co2-ppm)
  * https://frictionlessdata.io

I'm not sure what else!

How this might look when it is done? We scrape the data from the source, put into the data package, upload it the data hub platform and then use a plugin to get the data into our database for web API access. Once that data is in this open standard format, who knows all the ways it can be transformed. 

The important thing is to get it into the open standard format rather than just locked up in our database here.

**Comment by lwm** [comment]
The presentation from https://datahub.io/docs/core-data is very compelling.

**Comment by lwm** [comment]
It seems like a good first step would be: https://datahub.io/docs/getting-started/publishing-data

**Comment by lwm** [comment]
https://pkgstore.datahub.io/JohnSnowLabs/atmospheric-co2-trends-in-mauna-loa-mmd/atmospheric-co2-trends-in-mauna-loa-mmd-csv_csv/data/41ce1c204f6da17b178ef7b4b2894558/atmospheric-co2-trends-in-mauna-loa-mmd-csv_csv.csv

!!!!!!!!!!
