### ISSUE TITLE
Historical data points

### ISSUE THREAD

**Issue by lwm** [giving-a-fuck-about-climate-change/carbondoomsday#11]
Follows from https://github.com/giving-a-fuck-about-climate-change/carbon-doomsday/issues/3.

It'd be nice to start to compile some special dates but I was thinking that yes, we can do it, but there will always be more that some other people know. Therefore, we should support a nice interface to input some data point, which could go under some short review and be shown on whatever chart thereafter. 

We'd also start to gather a nice time line in this way from all different sources. I could do this just fine, create a model and a front-end could create a simple form. What do people think?

**Comment by titojankowski** [comment]
Here's a Google Sheet we can use to get our special dates started:
https://docs.google.com/spreadsheets/d/1Eu_fjLoBasqfsJw_mSQQTn219T6saUr_jtfrRKfaATM/edit#gid=0

To help gather datapoints from other people, I made a ["Climate Timeline Addition" Google Form](https://docs.google.com/forms/d/e/1FAIpQLSeiS4hK05JmRe4KWCzNH4RZqMawTgbLoeDQxb1G3inaVGHnWA/viewform) as a frontend to the sheet. 

Before we commit time to building a system, we can add a link to the form to gauge interest. Thoughts?

**Comment by lwm** [comment]
Sounds good to me! Time to collect :) I'll add a note to the README.
