### ISSUE TITLE
Deep linking to the All data graph

### ISSUE THREAD

**Issue by aphillipo** [giving-a-fuck-about-climate-change/carbondoomsday#110]
I want to be able link directly to the "All" graph as I find it even more fucking terrifying!

I'm happy to implement this myself and make a pull request.

Thanks!

**Comment by lwm** [comment]
Hey @aphillipo, sure! You mean, get the data of the "All" selection or actually embed the chart?

**Comment by aphillipo** [comment]
Just to be able to send a link to people (my Dad) showing the graph is going up at a crazily consistent rate since the 1960s.

**Comment by lwm** [comment]
Ah, I get it, thanks :) I've raised https://github.com/giving-a-fuck-about-climate-change/carbon-inferno/issues/163 for that. That is the repository where we have the front-end. Will close here. Thanks for checking out the project!

**Comment by lwm** [comment]
Done ins https://github.com/giving-a-fuck-about-climate-change/carbon-inferno/pull/174 @aphillipo!
