### ISSUE TITLE
Bake in some scalability into the deployment lest we see some action.

### ISSUE THREAD

**Issue by decentral1se** [giving-a-fuck-about-climate-change/carbondoomsday#111]
Raised by @eigenhombre over on the Gitter chat. A good point!

> any scalability to the deployment, in case it catches on?

Probably a pre-requisite of this is https://github.com/giving-a-fuck-about-climate-change/carbondoomsday/issues/100.

**Comment by eigenhombre** [comment]
From the Gitter chat:

"@lwm you can scale horizontally in DO but you'll need a load balancer I think. 
https://www.digitalocean.com/community/tutorials/how-to-automate-the-scaling-of-your-web-application-on-digitalocean-1404 I'm more familiar w/ the patterns in AWS but I expect there are similarities. 

"Another option might something be purely serverless (e.g. using S3 and Lambda), but would [probably] require a switch to AWS."

**Comment by lwm** [comment]
Note. I saw something like https://traefik.io/, which is cool (but doesn't support Dokku).
