### ISSUE TITLE
Broken link in contributing guidelines

### ISSUE THREAD

**Issue by Drazcmd** [giving-a-fuck-about-climate-change/carbondoomsday#116]
I believe this link in CONTRIBUTING.md is broken or incorrect:
https://docs.pipenv.org/en/latest/advanced.html#fancy-installation-of-pipenv 

Would need someone else to confirm, but I think we can probably just switch to use this one: http://pipenv.readthedocs.io/en/latest/install/#fancy-installation-of-pipenv

**Comment by Drazcmd** [comment]
Went ahead and tried all the other links to see if there were any problems, found one more broken one:
https://help.github.com/articles/fork-a-repo://help.github.com/articles/fork-a-repo/

Can probably just replace with
https://help.github.com/articles/fork-a-repo/

**Comment by lwm** [comment]
Thanks @Drazcmd! I'll fix this up.
