### ISSUE TITLE
Add new climate change related data

### ISSUE THREAD

**Issue by lwm** [giving-a-fuck-about-climate-change/carbondoomsday#12]
We currently just have CO2 measurements.

Some ideas we've had so far in our discussions:

  - [ ] Carbon footprint per person
  - [ ] Ice cap area over time
  - [ ] sea level visualization
  - [ ] Trends based on international agreements
  - [ ] Sea acidification levels

This django app is websockets ready, so we can support real-time data. Something to keep in mind!

Shout if you're hacking on something :+1:

**Comment by cathalgarvey** [comment]
So, some raw stuff from NOAA. Their data hub is very, very metadata-rich..but I don't really know if they have a "just give me the data" API anywhere, it's very unclear.

However, they do have [this world-map](https://www.pmel.noaa.gov/co2/map/index), where you can click on nodes and get a graph of ocean/air pH/CO2. And that data is ultimately pulled from a JSON API that follows the form:

`curl -s 'https://www.pmel.noaa.gov/co2/pco2data/graphite/{IDENTIFIER}_xco2.json?_=1498645822938'`

..where IDENTIFIER is a code for the measuring station. Not all of the measuring station codes I cleaned from the KML file return something at this URL, but some certainly do:

```bash
cathal@thinkum:~/Downloads$ egrep '/graphite/.+_public' basekml.kml | cut -d '_' -f 1 | cut -d '/' -f 7nh10
m2
seak
kodiak
gakoa
dabob
lapush
coastalms
nh
ndbcga
ndbcwa
cce2
twanoh
cheeca
chuukk1
hogreef
crescent
heronisland
laparguera
alawai
kilonalu
kaneohe
crimp2
crimp1
110w0
125w0
140w0
155w0
170w
165e0
165e8s
whots
stratus
cce1
keo
papa
boboa
sofs
iceland
jkeo
bats
mosean
```

The data returned includes the following fields, with the tail-end of the JSON containing an array of measurements over the specified time-frame (it's assumed, I guess, that the measurements are chronologically equidistant within that timeframe):

```bash
cathal@thinkum:~$ curl -s 'https://www.pmel.noaa.gov/co2/pco2data/graphite/seak_xco2.json?_=1498645822938' -H 'Accept: */*' -H 'Connection: keep-alive' | jq .deployment_meta.displaynames
[
  "System Number",
  "Pressure",
  "xCO2 of Seawater",
  "xCO2 of Air",
  "O2 Saturation",
  "Sea-Surface Temperature",
  "Sea-Surface Salinity",
  "Seawater pH",
  "Chlorophyll",
  "Turbidity",
  "Salinity-Compensated O2",
  "Salinity-Compensated O2",
  "Salinity-Compensated O2",
  "Sigma Theta",
  "Delta FCO2",
  "Delta PCO2",
  "Ωaragonite",
  "Ωaragonite (from TA)",
  "Ωaragonite (Mean)"
]
```

So.. that looks like it includes time-series data for lots of really interesting data. Presumably the "_" param can set the time-frame to display? I haven't experimented with that, yet.

This API obviously might not be stable, and a more "official" NOAA API would be better, if anyone can figure that out.

**Comment by cathalgarvey** [comment]
[This portal provides information about all of those measuring stations](https://www.pmel.noaa.gov/co2/map/text), and seems to use the same data API to access the measurements. So, probably the API is ~stable, if not official.

**Comment by cathalgarvey** [comment]
This acts as a directory for (open?) data portals covering air pollution, CO2, temperatures, and some other interesting data like snowfall (~albedo?): http://atmosphere.copernicus.eu/catalogue

**Comment by lwm** [comment]
@cathalgarvey, nice one for this. I'll start to pull some of this data soon.

**Comment by titojankowski** [comment]
We can go much deeper with carbon dioxide and build a real-time chart of all carbon dioxide on Earth!

NOAA has 100+ sites monitoring carbon dioxide we could pull: https://www.esrl.noaa.gov/gmd/dv/data/?parameter_name=Carbon%2BDioxide

There's hourly data from Antarctica!
ftp://aftp.cmdl.noaa.gov/data/trace_gases/co2/in-situ/surface/spo/co2_spo_surface-insitu_1_ccgg_HourlyData.txt

**Comment by lwm** [comment]
> We can go much deeper with carbon dioxide and build a real-time chart of all carbon dioxide on Earth!

Holy goat. That would be rad. Maybe we should focus on that? Anyone familiar with earth models (3D!?)? Or how would we show this across the earth ... some sort of heatmap or?

**Comment by titojankowski** [comment]
FWIW, there is 10-minute data available somewhere, at least 1958-2004:
http://scrippsco2.ucsd.edu/assets/publications/mauna_loa_report_high_frequency_co2_record_1958-2004.pdf

**Comment by lwm** [comment]
Well, we're kinda all over the place in this issue :)

As we've prioritised other things in the now, I'll go ahead and close.
