### ISSUE TITLE
`make test` should raise any linting errors

### ISSUE THREAD

**Issue by YPCrumble** [giving-a-fuck-about-climate-change/carbondoomsday#124]
Hey @lwm I'm having a little difficulty getting my `add_email_signature` PR to pass tests - one issue I'm facing is I've had some difficulty getting the environment and linting up and running exactly like you have it.

Currently `make test` is passing for me locally; it would be super helpful if this command included any linting you're doing on the CI server.

Sorry to be difficult! This whole pipenv thing is very new to me and I'm struggling to get it up and working.

**Comment by lwm** [comment]
> Sorry to be difficult!

No worries whatsoever. I'm happy your trying to make this easier to use.

I actually use the `make proof` target to run everything the CI does, have you seen it?

https://github.com/giving-a-fuck-about-climate-change/carbondoomsday/blob/8870c6a4a25f85d95adacd0e480cea74ff4d729f/Makefile#L23

**Comment by lwm** [comment]
RE: pipenv, you may want to give ttps://www.youtube.com/watch?v=GBQAKldqgZs a pass!
