### ISSUE TITLE
Scrape 'co2_mlo_mm.csv' as well!

### ISSUE THREAD

**Issue by lwm** [giving-a-fuck-about-climate-change/carbondoomsday#25]
@wickedwitch found this other source: https://www.esrl.noaa.gov/gmd/webdata/ccgg/trends/co2_mlo_mm.csv. It contains daily CO2 measurements from MLO! Once #24  gets merged, @wickedwitch will extend it/refactor to include the scraping of this data.

**Comment by lwm** [comment]
I've merged https://github.com/giving-a-fuck-about-climate-change/carbondoomsday/pull/24, go ahead :+1:

**Comment by lwm** [comment]
Actually, look at that data again, it's all on set to <year>-<date>-15. That looks wrong or!?

**Comment by titojankowski** [comment]
agreed looks the same to me, only data monthly data points for the 15th of each month.

**Comment by lwm** [comment]
Right, given the latest investigation, I think this data source won't work. 

Will close, re-open if I got it wrong!
