### ISSUE TITLE
Work on CSS and design (please, anyone!?)

### ISSUE THREAD

**Issue by lwm** [giving-a-fuck-about-climate-change/carbondoomsday#47]
We've got a really [nice mockup](https://files.gitter.im/giving-a-fuck-about-climate-change/Lobby/RC8C/Sketch1.png). The graph is being worked on in https://github.com/giving-a-fuck-about-climate-change/carbondoomsday/issues/43 but the rest of the design is needed. The general layout of the page, and responsiveness of the design. Anyone feeling it? I can help [in the Lobby](https://gitter.im/giving-a-fuck-about-climate-change/Lobby) with integrating bootstrap/styles with Django. So far, we have [this amazing template](https://github.com/giving-a-fuck-about-climate-change/carbondoomsday/blob/master/carbondoomsday/carbondioxide/templates/co2-tracker.html).

**Comment by titojankowski** [comment]
Pinging my friendz to help!

**Comment by lwm** [comment]
@grady-lad coming through with [the wire frame so far](https://files.gitter.im/giving-a-fuck-about-climate-change/Lobby/sCoJ/19531641_10154564592042321_1060218666_o.png)!

**Comment by lwm** [comment]
Head on over to https://github.com/giving-a-fuck-about-climate-change/carbon-inferno.
