### ISSUE TITLE
Document how to use the filters

### ISSUE THREAD

**Issue by lwm** [giving-a-fuck-about-climate-change/carbondoomsday#58]
They are very powerful once you know what works and what doesn't.

**Comment by titojankowski** [comment]
Agreed - add to "Implementation Notes" for now?

**Comment by lwm** [comment]
Yep, I think you got it in https://github.com/giving-a-fuck-about-climate-change/carbondoomsday/issues/59#issuecomment-316749715, so will close here and track there.
