### ISSUE TITLE
Somehow improve Swagger docs for 100+ filters

### ISSUE THREAD

**Issue by lwm** [giving-a-fuck-about-climate-change/carbondoomsday#59]
When viewing the Swagger documentation it is pretty hard to see what is available because so many filters are available. Perhaps we can improve this with an upstream patch.

**Comment by lwm** [comment]
I've created https://github.com/marcgibbons/django-rest-swagger/issues/677 to track this.

**Comment by titojankowski** [comment]
How about adding an "Example Usage" section to the "Implementation Notes"? Document basic sample queries like 
- pulling 1 year of data
- pulling most recent datapoint

and also cover date formatting yyyy-mm-dd and limit function/defaults

**Comment by titojankowski** [comment]
A friend suggests this alternate Swagger view, what do you think?
https://github.com/jensoleg/swagger-ui

**Comment by lwm** [comment]
> How about adding an "Example Usage" section to the "Implementation Notes"? 

Yes, will do that :+1:.

> A friend suggests this alternate Swagger view, what do you think?

Not sure if it would be easy. The  current UI is provided by a 3rd party library. Will check.

**Comment by titojankowski** [comment]
Once we have a >1 apps built on the API, an "app gallery" is worth re-considering:

Example: https://electron.atom.io/apps/

**Comment by lwm** [comment]
Done in https://github.com/giving-a-fuck-about-climate-change/carbondoomsday/pull/95.
