### ISSUE TITLE
Fix the recurring development notify issue

### ISSUE THREAD

**Issue by lwm** [giving-a-fuck-about-climate-change/carbondoomsday#69]
As mentioned by @titojankowski, the Gitter webhook notify for tasks might be buggy.

I just saw:

![image](https://user-images.githubusercontent.com/1991377/28480214-eb12094c-6e5f-11e7-99c4-6cd6c3a43dcd.png)

Where the listing on the right side bar has:

```
Development: daily-mlo-co2-since-2015 didn't find any fresh data today
```

Actually, I've added some code that should ban doing this from development, so this is a bug, or someone is using an old version of it locally. I doubt this though. It seems to coincide with a Heroku release ...

**Comment by lwm** [comment]
Following a check on the admin of both test:

![image](https://user-images.githubusercontent.com/1991377/28480321-64372906-6e60-11e7-92e0-678e29c0db06.png)

And production:

![image](https://user-images.githubusercontent.com/1991377/28480331-6dabc0e6-6e60-11e7-9de9-aa2e9683468d.png)



 I see that no new objects have been created. So I have no idea where this is being run. @grady-lad, are you using an old version of the back-end source code?

**Comment by grady-lad** [comment]
could be me :)

**Comment by lwm** [comment]
Clooosssiiinnggggg! :beers:  (git pull upstream!)
