### ISSUE TITLE
5 days since fresh data

### ISSUE THREAD

**Issue by titojankowski** [giving-a-fuck-about-climate-change/carbondoomsday#74]
Current most recent data points in production and shown on front-end is 2017-07-22: https://www.dropbox.com/s/vim7ab97klzpkfx/Screenshot%202017-07-28%2020.29.01.png?dl=0

However, daily measurements for 07-23, 07-25, 07-26, and 07-27 are online in [co2_mlo_weekly.csv]: https://www.dropbox.com/s/a6qmfexvd4gw2e3/Screenshot%202017-07-28%2020.21.29.png?dl=0

carbondoomsday-test also hasn't been updated for 7 days, 2017-07-20:
https://www.dropbox.com/s/ztnmukharmzn0ha/Screenshot%202017-07-28%2020.28.23.png?dl=0

What's up with that? Relates to [#70]?

**Comment by lwm** [comment]
So, I've made a new release which makes the scrape run every 3 hours as opposed to 12 hours, which I thought was the problem described in https://github.com/giving-a-fuck-about-climate-change/carbondoomsday/issues/70#issuecomment-318470987. I've updated with fresh data and will keep an eye on it. If this doesn't fix it, it's probably some Heroku platform thing I'm missing :)

**Comment by titojankowski** [comment]
Updates every 30 minutes as long as the dyno is running woot woot!
