### ISSUE TITLE
Inconsistent data between MLO and carbondoomsday (6 examples)

### ISSUE THREAD

**Issue by titojankowski** [giving-a-fuck-about-climate-change/carbondoomsday#75]
Dataset shows **407.24**
https://www.esrl.noaa.gov/gmd/webdata/ccgg/trends/co2_mlo_weekly.csv: 
Screenshot: https://www.dropbox.com/s/krvwrdr3227e24h/Screenshot%202017-07-29%2020.17.21.png?dl=0

carbondoomsday.com shows **407.77**:
Screenshot: https://www.dropbox.com/s/7w9kqlyxafmyn5y/Screenshot%202017-07-29%2020.18.33.png?dl=0

**Comment by titojankowski** [comment]
Found 3 more examples in the past month (see below), and even differences looking back to 2016:

3 examples from June 2017, sampling of 30 days in June 1 - 30, 2017

_Example Format:
Django data
ESRL data (https://www.esrl.noaa.gov/gmd/webdata/ccgg/trends/co2_mlo_weekly.csv)_

Example 1.
June 10, 2017 | _409.62_
2017-06-10,_409.15_,408.84,409.65

Example 2.
June 17, 2017 408.82
2017-06-17,408.74,408.84,409.39

Example 3.
June 24, 2017 | 408.42
2017-06-24,408.36,408.84,408.26

Looking more than a year back, June 1 - 30, **2016**

Example 4.
June 4, 2016 | 407.52
2016-06-04,,406.81,407.53

Example 5.
June 11, 2016 | 406.99
2016-06-11,407.4,406.81,406.86

Example 6.
June 18, 2016 | 407.02
2016-06-18,406.92,406.81,407.2

@lwm what's going on, is this an issue with our import? Or is MLO updating the data...even a year later in the case of the June 2016 data? Potentially they are with good reason of course. 

Do we have the capability to run a complete scan of our data and "update" changed records, while still maintaining the record of the old value? This is interesting because this is non-public data since MLO doesn't publish a changelog. Potentially makes our dataset unique and more valuable to researchers than just the public data!

(updating title to reflect more data points)

**Comment by titojankowski** [comment]
Is it just production, or is test database also affected?
- Both have the same data. Examples 1, 2, 3, 4, 5, 6 all match between production and test

What about data from further back in other datasets?
- I looked at the period 1996-12-01 to 1996-12-31 in the older datasets. I found none of the types of changes featured. (However, I found that weekly and daily datapoints from 2 files were mixed together which is somewhat confusing, will add as separate issue.)

**So overall, it looks like data from [co2_mlo_weekly.csv] may be changing, even a year later**

**Comment by lwm** [comment]
> @lwm what's going on, is this an issue with our import? Or is MLO updating the data...even a year later in the case of the June 2016 data? Potentially they are with good reason of course, they have warned that the data does change and get updated.

On the first run, the data import runs, sucking in date and ppm value. On the following runs, if a database entry exists for a given date, we skip inserting anything and keep going - only getting new entries. So, yes, if MLO are updating data, we are not getting the updated values.

> Do we have the capability to run a complete scan of our data and "update" changed records, while still maintaining the record of the old value? This is interesting because this data isn't available, MLO doesn't publish a changelog. Having this record would make our dataset unique. More valuable to researchers than just the public data on the FTP server.

This would involve quite a bit of work. Yes, it this would be a unique feature of our data source but for what purpose? How is that valuable?

> Is it just production, or is test database also affected?

It should be the same values. It does of course depend on if the app is alive (Heroku free tier dynos) and that the scrape has ran. The functionality is the same in the end.

**Comment by titojankowski** [comment]
Makes sense, thanks for the explanation! Biggest opportunity is that we tell people this is how it all works. 

Where should the description of this go in the documentation?

**Comment by lwm** [comment]
> Where should the description of this go in the documentation?

Yes, I need to find some documentation solution for adding this all.
