### ISSUE TITLE
Weekly and daily data mixed

### ISSUE THREAD

**Issue by titojankowski** [giving-a-fuck-about-climate-change/carbondoomsday#76]
Comparing production to our datasets, we are merging weekly and daily datasets. In this case, daily data is being overwritten with a weekly calculation. weekly_in_situ_co2_mlo.csv is weekly data, not daily data, and I'm not sure how it's calculated either.

2 examples below:
_Example format
Production data
DailyData.txt (ftp://aftp.cmdl.noaa.gov/data/trace_gases/co2/in-situ/surface/mlo/co2_mlo_surface-insitu_1_ccgg_DailyData.txt)
weekly_in_situ_co2_mlo.csv (http://scrippsco2.ucsd.edu/assets/data/atmospheric/stations/in_situ_co2/weekly/weekly_in_situ_co2_mlo.csv)_

Production: Nov. 30, 1996 | **361.40**
DailyData.txt: MLO 1996 11 30 0 0 0 **361.47** 0.08 21 19.536 -155.576 3437.0 3397.0 40.0 NA ...
weekly_in_situ_co2_mlo.csv: 1996-11-30, **361.40**

Production: Dec. 7, 1996 | **361.97**
DailyData.txt: MLO 1996 12 7 0 0 0 **361.82** 0.26 11 19.536 -155.576 3437.0 3397.0 40.0 NA ...
weekly_in_situ_co2_mlo.csv: 1996-12-07, **361.97**

Thoughts on resolving this? At this point our data structure only supports one data point per day. So in that case I would propose removing weekly_in_situ_co2_mlo.csv since it is weekly data, and our dataset should stick to daily measurements throughout for consistency. Harder option is have a separate table of "weekly" and "daily" measurements.

Priority: Doesn't seem super high priority. Important for moving forwards and ensuring quality data and keeping track of what all this data is and where it came from.

Thoughts @lwm?

**Comment by lwm** [comment]
> Comparing production to our datasets, we are merging weekly and daily datasets. In this case, daily data is being overwritten with a weekly calculation.

No overwriting is happening. On new scrapes, no old value is changed, only new values are added.

> weekly_in_situ_co2_mlo.csv is weekly data, not daily data

Yep, but they still provide a measurement for a day. We just take the measurement for each day they record. If we haven't scraped a value from another source for this day, we grab it.

As mentioned before (somewhere in a comment), we're mixing data sets and just saying "we're getting data from all these sources from MLO" and not giving fine grain source for each measurement.

**Comment by titojankowski** [comment]
Good explanation, thanks! One other option is to drop weekly_in_situ_co2_mlo.csv as a data source, since it's not daily data but a weekly average.

Overall, I'm comfortable just leaving all of this as is for now, as long as we document it. Let's find someone who uses the data and get them to help prioritize and architect this.

**Comment by lwm** [comment]
> One other option is to drop weekly_in_situ_co2_mlo.csv as a data source, since it's not daily data but a weekly average.

Are you sure of that? I think it's just a value taken each week, not an average?

> Let's find someone who uses the data and get them to help prioritize and architect this.

:tada:

**Comment by titojankowski** [comment]
> Are you sure of that? I think it's just a value taken each week, not an average?

Nah, I'm not really sure hehe. ESRL's website (which is not the same as Scripp's website however), suggests ESRL's weekly datapoint is an average.

From [ESRL's website](https://www.esrl.noaa.gov/gmd/ccgg/trends/weekly.html):

> The weekly mean (red bar) is simply the average of all days in the week for which a background value could be defined. The average standard deviation of day to day variability, calculated as the difference from the appropriate weekly mean, equals 0.38 ppm for the entire record.

The dataset itself is vague:

> " The data file below contains 2 columns indicaing the date and CO2      "
> " concentrations in micro-mol CO2 per mole (ppm), reported on the 2008A  "
> " SIO manometric mole fraction scale.  These weekly values have been     "
> " adjusted to 12:00 hours at middle day of each weekly period as         "
> " indicated by the date in the first column.

**Comment by lwm** [comment]
> The dataset itself is vague

I've added this question [to our google doc](https://docs.google.com/document/d/141VeLvFLl4cV20jIOU3giUeDFJACgaFSDNO9tIwiPGc/edit#) so maybe if you get a chance, you can find out more about this data set. Will close this off now but do follow up if you find out more.

I created https://github.com/giving-a-fuck-about-climate-change/carbondoomsday/issues/78 and https://github.com/giving-a-fuck-about-climate-change/carbondoomsday/issues/77 based on your last two tickets :+1: :+1: :+1:
