### ISSUE TITLE
Roll some narrative documentation

### ISSUE THREAD

**Issue by lwm** [giving-a-fuck-about-climate-change/carbondoomsday#77]
Following from https://github.com/giving-a-fuck-about-climate-change/carbondoomsday/issues/75#issuecomment-318923325, we should find a nice solution for some 'narrative' style documentation that shows the inner workings of the how we get data.

**Comment by lwm** [comment]
https://github.com/giving-a-fuck-about-climate-change/carbondoomsday/issues/60 and https://github.com/giving-a-fuck-about-climate-change/carbondoomsday/issues/59 are related.

**Comment by titojankowski** [comment]
Got an example in mind we could use as inspiration?

**Comment by lwm** [comment]
> Got an example in mind we could use as inspiration?

https://stripe.com/docs/api is pretty amazing.

**Comment by lwm** [comment]
As far as I can see, we're doing this via carbon-infero (data sources pages for example).

So will close here.
