### ISSUE TITLE
Get the docker-compose setup working

### ISSUE THREAD

**Issue by lwm** [giving-a-fuck-about-climate-change/carbondoomsday#8]
Ideally, people hacking on this can run the whole thing by running `docker-compose up`.

**Comment by titojankowski** [comment]
just a quick ping that it took me about 10 minutes to get setup, i had github desktop already installed, so added the django repository, downloading and installing docker was easy. docker-compose up works as promised! there's a frontend UI @ 127.0.0.01:8089 where you can manually type a query to test it out, or if you try it through the API like a prototype would use (ie http://127.0.0.1:8089/api/co2/?date=06%2F14%2F2017) it come backs with sweet sweet co2 data.

**Comment by lwm** [comment]
> ... with sweet sweet co2 data.

Feels good. We're getting there! :)
