### ISSUE TITLE
API suggests URL with "offset"

### ISSUE THREAD

**Issue by titojankowski** [giving-a-fuck-about-climate-change/carbondoomsday#84]
The API docs return a sample URL where you can get the results. ie:
http://api.carbondoomsday.com/api/co2/?date__gte=2016-12-01&limit=50&offset=50

However, the "offset" thing trims the first 50 data points off. I don't see any reason why we would want that? If you load that request, the data starts on 2017-10-04 (trimming off the 50 most recent data points). My thought is to remove offset entirely, it's just confusing. Thoughts @lwm ?

**Comment by lwm** [comment]
Oh yes, that is a bit weird. I think I chose the wrong paginator? We have http://www.django-rest-framework.org/api-guide/pagination/#limitoffsetpagination now but perhaps we just want plain 'ol http://www.django-rest-framework.org/api-guide/pagination/#pagenumberpagination.

**Comment by grady-lad** [comment]
We are not using the offset param in the fe, from what I can see,  so could this be updated without breaking the fe ?

**Comment by lwm** [comment]
OK, I'll try and do this later then. Hopefully it won't break things 🍻

**Comment by lwm** [comment]
@grady-lad, @stephanieinez from https://github.com/giving-a-fuck-about-climate-change/carbon-inferno/issues/124#issuecomment-349790456, I can see you're using the `limit` keyword - this will be gone with this change. From [the documentation](http://www.django-rest-framework.org/api-guide/pagination/#limitoffsetpagination), I read that the `page_size` keyword functions the same. This will then be a breaking change.

So, here's what I propose:
  * Build a branch on carbon-inferno which uses `page_size` parameter
  * Wait until I fix https://github.com/giving-a-fuck-about-climate-change/carbondoomsday/issues/88 and get the build back in order
  * We'll pick a time and make a feature release together and make sure it works.

How does it sound?

**Comment by lwm** [comment]
Fruit cake, I merged it  by accident. However, I believe I preserved the `limit` setup after all. Phew!
