### ISSUE TITLE
Fix broken cache and cors tests

### ISSUE THREAD

**Issue by lwm** [giving-a-fuck-about-climate-change/carbondoomsday#88]
Not sure if affecting production, hopefully @grady-lad can report.

First seen on https://travis-ci.org/giving-a-fuck-about-climate-change/carbondoomsday/jobs/312405320.

**Comment by grady-lad** [comment]
I am not following ? what can I report ?

**Comment by lwm** [comment]
Ah, sorry, wasn't clear. Basically, if the cache was still working and if CORs headers were still there.

It seems like the site is now broken because CORS headers are not being sent.
