### ISSUE TITLE
Investigate what needs to be done for Heroku setup

### ISSUE THREAD

**Issue by lwm** [giving-a-fuck-about-climate-change/carbondoomsday#9]

**Comment by titojankowski** [comment]
We've got a heroku account heroku@carbondoomsday, anyone interested email me for the pass (tito@titojankowski.com). Luke and Elliott already have it as well.

**Comment by titojankowski** [comment]
This is a great next milestone, we can launch it as "the world's first open API for carbon dioxide"!

Could get some solid press and collaborators.

**Comment by lwm** [comment]
She's up! https://carbondoomsday-test.herokuapp.com/

**Comment by lwm** [comment]
And the production instance https://carbondoomsday.herokuapp.com/.
