### ISSUE TITLE
Stop using Heroku

### ISSUE THREAD

**Issue by lwm** [giving-a-fuck-about-climate-change/carbondoomsday#97]
It is too expensive and I can probably just self host this. Must do this soon.

Mega thanks to @titojankowski for footing the bill so far!!!

**Comment by titojankowski** [comment]
my pleasure!

**Comment by grady-lad** [comment]
How much is this costing us at the moment ?

**Comment by grady-lad** [comment]
oops for closing the issue 😄

**Comment by titojankowski** [comment]
@grady-lad $25/month
carbon-inferno: $7
carbondoomsday: $9
carbondoomsday-test: $9

@lwm are we still using carbondoomsday-test?

**Comment by lwm** [comment]
Yep, we're still using it - it's probably overkill since we can just move stuff into production and roll back as we are hacking on it. Feel free to kill it.

**Comment by lwm** [comment]
HERES THE PLAN:

  * Get the $5 toaster from https://www.digitalocean.com/pricing/
  * Use http://dokku.viewdocs.io/dokku/ to pretend to be Heroku (manage deployments)
  * Set it up
  * SAVE MONEY

Going for this now.

**Comment by titojankowski** [comment]
I can cover the digital ocean $, lmk the login. dokku looks interesting,
DIY Heroku. What are the pros/cons of using dokku instead of heroku?
Pro: 
1. Cheaper, replaces all heroku? ($5 vs $30/month

Con:
1. Deploy: Is it harder to get new projects up and running? Do we still
   get updates in gitter about deployment?2. Managing: Doesn’t seem like we’ve used any of Heroku’s features
   besides “pay more monehhh”. From an admin perspective it has a pretty
   dashboard I’ve glanced st...but Google Analytics should be the real
   dashboard.

On Sun, Jan 28, 2018, at 6:03 AM, Luke Murphy wrote:
> HERES THE PLAN:


>  * Get the $5 toaster from https://www.digitalocean.com/pricing/
>  * Use http://dokku.viewdocs.io/dokku/ to pretend to be Heroku (manage
>    deployments)
>  * Set it up
>  * SAVE MONEY> Going for this now.


> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[1], or mute the thread[2].> 


Links:

  1. https://github.com/giving-a-fuck-about-climate-change/carbondoomsday/issues/97#issuecomment-361065326

**Comment by lwm** [comment]
> Deploy: Is it harder to get new projects up and running? 
> Do we still get updates in gitter about deployment?

It's the same flo - just `git push origin master` and the application auto-magically deploys! Yes, the update request will still fire and is independent of the deployment.

Yeah, we need a better dashboard to see usage and get better overview. Since we control the machine that the application will run (digital ocean just gives you a full machine), we can install https://matomo.org/ (ethical, free software analytics) and set that up!

**Comment by lwm** [comment]
Yes, Heroku is a bug.

**Comment by lwm** [comment]
Some documentation along the way! https://github.com/dokku/dokku/pull/3059.

**Comment by lwm** [comment]
It's up! http://178.62.103.145:2203/

**Comment by gthole** [comment]
Here via Hacker News.  Thank you for this.

For what it's worth, this could also be hosted on AWS in the free tier.

- Cloudformation CDN for web static assets
- API Gateway & Lambda for API calls
- Terraform for deployment

Infinite scale for when the world suddenly starts realizing that climate change threatens our very existence.

I set up [a site with the above deployment mechanincs](https://github.com/bostoncan/community-choice-boston) for the Boston Climate Action Network and could be willing to take a look at putting together a similar setup (and possibly hosting) for this site.

**Comment by lwm** [comment]
Thanks for the points @gthole! It's great that you are providing infrastructure for movements.

> Infinite scale

I think there is no infinite scale (no cloud just someone else's computer) and that this kind of thinking is getting us into such a position in the first place. AWS play a significant role in making the problem worse with their so-called ['dirty cloud'](https://www.greenpeace.org/archive-international/en/campaigns/climate-change/cool-it/amazon-failing-to-admit-its-dirty-cloud-probl/blog/41118/).

We're in the middle of getting this onto a lean digital ocean machine right now by the way!

**Comment by gthole** [comment]
Okey doke - good luck out there!

**Comment by eigenhombre** [comment]
Just to reinforce what @gthole suggested, I have [an (unrelated) API](https://github.com/eigenhombre/trav) which runs 24/7, is very quick to respond, deployed via Terraform, and which costs me about a US nickel (US$0.05) per month.  I'm not a total fanboy of AWS but serverless has real advantages in terms of cost and scalability if you are footing the bill.  Perhaps someone could estimate the CPU/kWh costs for such a deployment (I'm guessing they are substantially lower than for VMs) and carbon offsets could be purchased to get to neutrality.

**Comment by lwm** [comment]
Thanks @eigenhombre. Again, I have a principled objection to using AWS and I am sure we can get the same benefits from another provider. Where feasible, I like to dogfood on ways we can make choices with positive results on the question of climate change. I recognise it is not always possible or making sense, but this seems like an easy one.

You both (@eigenhombre @gthole) seem quite interested in this deployment issue, I would love to have your help! Any motivation to join on a 'deploy' team under the organisation and lend a hand with getting it out the door + monitoring it? No worries if not!

**Comment by eigenhombre** [comment]
Understood @lwm ... I am interested in principle though have somewhat limited availability.

**Comment by lwm** [comment]
ACHIEVED! We currently have two apps managed by Dokku fully migrated from Heroku and with a decent SSL setup so far. That'll do for now on this issue. More to come, thanks all for weighing in here!
